disabled_rules:
- leading_whitespace
- trailing_whitespace
- line_length

type_name:
    min_length:
        warning: 1
    max_length:
        warning: 80
        error: 100

identifier_name:
    min_length:
        warning: 1

excluded:
- MovieReview/AppDelegate.swift
- MovieReview/SceneDelegate.swift
- Pods

